dist: bionic

language: rust

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python3-setuptools
  - pip3 install --user online-judge-verify-helper

script: ./ci.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./target/doc
  keep_history: true
  on:
    branch: master
