[languages.rs]
compile = "cargo build --examples --release"
execute = "bash -c \\'cargo run --quiet --example $(basename {path} .rs) --release\\'"
bundle = "false"
list_attributes = "sed 's|^// verify-helper: ||; t; d' {path}"
list_dependencies = "true"
